In [14]:
import numpy as np
#function for Jacobi method
def jacobi(A, b, x0, tol, max_iterations):
    n = len(b)
    x = x0.copy()
    for k in range(max_iterations):
        x_new = np.zeros_like(x)
        for i in range(n):
            s = sum(A[i][j] * x[j] for j in range(n) if j != i)
            x_new[i] = (b[i] - s) / A[i][i]
        # Check for convergence
        if np.linalg.norm(x_new - x, ord=np.inf) < tol:
            return x_new, k
        x = x_new
    return x, max_iterations

#function for Gauss-Seidel method
def gauss_seidel(A, b, x0, tol, max_iterations):
    n = len(b)
    x = x0.copy()
    for k in range(max_iterations):
        x_new = x.copy()
        for i in range(n):
            s1 = sum(A[i][j] * x_new[j] for j in range(i)) # Using already updated values
            s2 = sum(A[i][j] * x[j] for j in range(i + 1, n)) # Using old values
            x_new[i] = (b[i] - s1 - s2) / A[i][i]
        # Check for convergence
        if np.linalg.norm(x_new - x, ord=np.inf) < tol:
            return x_new, k
        x = x_new
    return x, max_iterations

In [15]:
#challenge a
import time
A = np.array([
	[0.582745, 0.48	, 0.10	, 0.  	, 0.  	], 
 [0.48	, 1.044129, 0.46	, 0.10	, 0.  	],
 [0.10	, 0.46	, 1.10431 , 0.44	, 0.10	],
 [0.  	, 0.10	, 0.44	, 0.963889, 0.42	],
 [0.  	, 0.  	, 0.10	, 0.42	, 0.522565]], dtype=float)
b = np.array([1.162745, 2.084129, 2.20431 , 1.923889, 1.042565], dtype=float)

x0 = np.zeros_like(b)
tol = 1e-6
max_iterations = 1000

#sovle using Jacobi
start_j = time.time()
sol_j, iter_j = jacobi(A, b, x0, tol, max_iterations)
end_j = time.time()

#solve using Gauss Sidel
start_g = time.time()
sol_g, iter_g = gauss_seidel(A, b, x0, tol, max_iterations)
end_g = time.time()

#show results
print(f'Jacobi: solution: {sol_j}, iterations: {iter_j}, Time: {end_j - start_j:.6f}s')
print(f'Gauss Sidel: solution: {sol_g}, iterations: {iter_g}, Time: {end_g - start_g:.6f}s')

Jacobi: solution: [0.9848677  0.98485984 0.98485878 0.98486297 0.98487321], iterations: 1000, Time: 0.049794s
Gauss Sidel: solution: [0.99999926 1.00000045 0.99999989 0.99999997 1.00000005], iterations: 20, Time: 0.001124s


In [16]:
#challenge b
A = np.array([[1, 	1], [1, 1.0001]])
b = np.array([1, 1])
x0 = np.zeros_like(b)
tol = 1e-6
max_iterations = 1000

#sovle using Jacobi
start_j = time.time()
sol_j, iter_j = jacobi(A, b, x0, tol, max_iterations)
end_j = time.time()

#solve using Gauss Sidel
start_g = time.time()
sol_g, iter_g = gauss_seidel(A, b, x0, tol, max_iterations)
end_g = time.time()

#show results
print(f'Jacobi: solution: {sol_j}, iterations: {iter_j}, Time: {end_j - start_j:.6f}s')
print(f'Gauss Sidel: solution: {sol_g}, iterations: {iter_g}, Time: {end_g - start_g:.6f}s')

Jacobi: solution: [1 0], iterations: 1, Time: 0.000383s
Gauss Sidel: solution: [1 0], iterations: 1, Time: 0.000251s


In [17]:
#challenge c
A = np.array([[1, 	1], [1, 1.0001]])
b = np.array([1, 1.0001])
x0 = np.zeros_like(b)
tol = 1e-6
max_iterations = 1000

#sovle using Jacobi
start_j = time.time()
sol_j, iter_j = jacobi(A, b, x0, tol, max_iterations)
end_j = time.time()

#solve using Gauss Sidel
start_g = time.time()
sol_g, iter_g = gauss_seidel(A, b, x0, tol, max_iterations)
end_g = time.time()

#show results
print(f'Jacobi: solution: {sol_j}, iterations: {iter_j}, Time: {end_j - start_j:.6f}s')
print(f'Gauss Sidel: solution: {sol_g}, iterations: {iter_g}, Time: {end_g - start_g:.6f}s')

Jacobi: solution: [0.        0.0487682], iterations: 1000, Time: 0.031823s
Gauss Sidel: solution: [0.90493243 0.09515806], iterations: 1000, Time: 0.020197s


In [18]:
#in class challenge
def diagonally_dominant(A):
    print(A)
    diagonal = np.abs(np.diag(A))
    row_sums = np.sum(np.abs(A), axis=1)
    off_diag_sums = row_sums - diagonal
    result = np.all(diagonal > off_diag_sums)
    print(f'Is the matrix diagonally dominant? {result}')

In [19]:
A = np.array([[10, -1, 2, 0, 0],
             [-1, 11, -1, 3, 0],
             [2, -1, 10, -1, 0],
             [0, 3, -1, 8, -2],
             [0, 0, 0, -2, 9]])
diagonally_dominant(A)
print()
A = np.array([[1, 2, 3, 0, 0],
            [2, 1, 2, 3, 0],
            [3, 2, 1, 2, 3],
            [0, 3, 2, 1, 2],
            [0, 0, 3, 2, 1]])
diagonally_dominant(A)

[[10 -1  2  0  0]
 [-1 11 -1  3  0]
 [ 2 -1 10 -1  0]
 [ 0  3 -1  8 -2]
 [ 0  0  0 -2  9]]
Is the matrix diagonally dominant? True

[[1 2 3 0 0]
 [2 1 2 3 0]
 [3 2 1 2 3]
 [0 3 2 1 2]
 [0 0 3 2 1]]
Is the matrix diagonally dominant? False
