In [2]:
import numpy as np

In [3]:
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])

In [4]:
print (v1)
print (v2)

[1 2 3]
[4 5 6]


In [5]:
v_add = v1+v2
v_sub = v1-v2
print(v_add)
print(v_sub)

[5 7 9]
[-3 -3 -3]


In [7]:
scalar = 2
v_scaled = scalar*v1
print(v_scaled)

[2 4 6]


In [8]:
dot_product = np.dot(v1,v2)
print(dot_product)

32


In [10]:
magnitude_v1 = np.linalg.norm(v1)
print("Magnitude of v1: ",magnitude_v1)

Magnitude of v1:  3.7416573867739413


In [11]:
A = np.array([[1,2,3],[4,5,6]])
print(A)
B = np.array([[7,8,9],[10,11,12],[13,14,15]])
print(B)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [15]:
C = np.array([[1,3,4],[4,5,6]])
matrix_add = A + C
matrix_sub = A - C
print("A+C = \n",matrix_add)
print("A-C = \n",matrix_sub)

A+C = 
 [[ 2  5  7]
 [ 8 10 12]]
A-C = 
 [[ 0 -1 -1]
 [ 0  0  0]]


In [16]:
matrix_mul = np.dot(A, B)
print(matrix_mul)

[[ 66  72  78]
 [156 171 186]]


In [18]:
transpose_A = A.T
print(transpose_A)

[[1 4]
 [2 5]
 [3 6]]


In [19]:
A = np.array([[2,3],[4,-1]])
b = np.array([5,3])
x = np.linalg.solve(A,b)
print("Solution (x,y): ",x)

Solution (x,y):  [1. 1.]


In [4]:
A = np.array([[2,1],[1,2]])
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues: [3. 1.]
Eigenvectors:
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [6]:
A = np.array([[4,7],[2,6]])
A_inv = np.linalg.inv(A)
print("Inverse of A:\n",A_inv)
identity = np.dot(A, A_inv)
print("A * A_inv:\n", identity)

Inverse of A:
 [[ 0.6 -0.7]
 [-0.2  0.4]]
A * A_inv:
 [[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]
